CREATE TABLE CLIENTE (
	COD_CLI INT PRIMARY KEY AUTO_INCREMENT,
    NOME_CLI VARCHAR(150) NOT NULL,
    CPF_CLI VARCHAR(11) NOT NULL UNIQUE,
    RG_CLI VARCHAR(14) UNIQUE,
    DATA_NASC_CLI DATE NOT NULL,
    EMAIL_CLI VARCHAR (200) NOT NULL UNIQUE,
    TELEFONE_CLI VARCHAR(15),
    SENHA_CLI VARCHAR(255) NOT NULL
);

CREATE TABLE ASSINATURA (
	COD_CLI INT NOT NULL PRIMARY KEY, -- pk e fk
    STATUS_ASS ENUM('Ativa', 'Vencida', 'Inativa') NOT NULL, 
    PLANO_ASS VARCHAR(20) NOT NULL, 
    VENC_ASS DATE NOT NULL,
    CONSTRAINT fk_cli_cod FOREIGN KEY (COD_CLI) REFERENCES CLIENTE (COD_CLI)
);

CREATE TABLE FUNCIONARIO (
	COD_FUN INT PRIMARY KEY AUTO_INCREMENT,
    STATUS_FUNC ENUM('Ativo', 'Inativo', 'Afastado', 'Férias') NOT NULL,
    NOME_FUN VARCHAR (150) NOT NULL,
    MATRICULA_FUN VARCHAR(4) NOT NULL UNIQUE,
    CARGO_FUN VARCHAR(30) NOT NULL
);

CREATE TABLE FORNECEDOR (
	COD_FOR INT PRIMARY KEY AUTO_INCREMENT,
    CNPJ_FOR VARCHAR(14) NOT NULL UNIQUE,
    RAZAO_FOR VARCHAR(60) NOT NULL UNIQUE,
    NOME_FAN_FOR VARCHAR(60),
    EMAIL_FOR VARCHAR(200) NOT NULL UNIQUE,
    TELEFONE_FOR VARCHAR(15) NOT NULL
);

-- CREATE TABLE FORNECEDOR_PRODUTO (); -- talvez exista, por enquanto fornecedor não é associado a nada

CREATE TABLE ENDERECO (
	COD_END INT PRIMARY KEY AUTO_INCREMENT, -- pensando que um cliente/fornecedor pode ter mais de um endereço, precisa de um identificador unico para diferenciar
	COD_CLI INT,
    COD_FOR INT, -- esse ou o outro vai estar com o id
    RUA_END VARCHAR(255) NOT NULL,
    NUM_END VARCHAR (25),
    BAIRRO_END VARCHAR(255) NOT NULL,
    CIDADE_END VARCHAR (255) NOT NULL,
    ESTADO_END VARCHAR (2) NOT NULL,
    CEP_END VARCHAR(8) NOT NULL,
    CONSTRAINT fk_end_cli FOREIGN KEY (COD_CLI) REFERENCES CLIENTE (COD_CLI),
    CONSTRAINT fk_end_for FOREIGN KEY (COD_FOR) REFERENCES FORNECEDOR (COD_FOR),
    CHECK ((COD_CLI IS NOT NULL AND COD_FOR IS NULL) OR (COD_FOR IS NOT NULL AND COD_CLI IS NULL)) -- cliente ou fornecedor
);

CREATE TABLE CATEGORIA (
	COD_CAT INT PRIMARY KEY AUTO_INCREMENT,
    NOME_CAT VARCHAR (50) NOT NULL UNIQUE
);

CREATE TABLE MARCA (
	COD_MAR INT PRIMARY KEY AUTO_INCREMENT,
    NOME_MAR VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE PRODUTO (
	COD_PROD INT PRIMARY KEY AUTO_INCREMENT,
    COD_MAR INT NOT NULL,
    COD_CAT INT NOT NULL,
	NOME_PROD VARCHAR(100) NOT NULL,
    DESC_RED_PROD VARCHAR(255) NOT NULL, -- descrição reduzida (presente no site)
    DESC_PROD TEXT NOT NULL,
    UNI_MEDIDA_PROD ENUM('KG', 'G', 'UN', 'L', 'ML') NOT NULL,
    VALOR_UNI_PROD NUMERIC(6, 2) NOT NULL,
    CONSTRAINT fk_prod_mar FOREIGN KEY (COD_MAR) REFERENCES MARCA (COD_MAR),
    CONSTRAINT fk_prod_cat FOREIGN KEY (COD_CAT) REFERENCES CATEGORIA (COD_CAT),
    CHECK (VALOR_UNI_PROD >= 0),
    CHECK (EST_PROD >= 0)
);

CREATE TABLE PROMOCAO (
	COD_PROMO INT PRIMARY KEY AUTO_INCREMENT,
    NOME_PROMO VARCHAR(100) NOT NULL,
    TIPO_PROMO ENUM('Manual', 'Vencimento') DEFAULT 'Manual' NOT NULL,
    DESCONT_MON_PROMO NUMERIC(8, 2),
    DESCONT_PER_PROMO NUMERIC(5, 2),
    DATA_INIC_PROMO DATE NOT NULL,
    DATA_FIM_PROMO DATE NOT NULL,
    CHECK (DATA_FIM_PROMO >= DATA_INIC_PROMO),
    CHECK (DESCONT_MON_PROMO IS NULL OR DESCONT_MON_PROMO > 0),
    CHECK (DESCONT_PER_PROMO IS NULL OR (DESCONT_PER_PROMO > 0 AND DESCONT_PER_PROMO <= 100)),
	CHECK ((DESCONT_MON_PROMO IS NOT NULL AND DESCONT_PER_PROMO IS NULL) OR (DESCONT_PER_PROMO IS NOT NULL AND DESCONT_MON_PROMO IS NULL))
);


CREATE TABLE LOTE (
    COD_LOTE INT PRIMARY KEY AUTO_INCREMENT,

    COD_PROD INT NOT NULL,
    COD_PROMO INT,

    NUM_LOTE VARCHAR(50) NOT NULL,

    DATA_FAB_LOTE DATE,
    DATA_VENC_LOTE DATE NOT NULL,

    EST_LOTE NUMERIC(10, 2) NOT NULL,

    CONSTRAINT fk_lote_prod
        FOREIGN KEY (COD_PROD)
        REFERENCES PRODUTO (COD_PROD),

    CONSTRAINT fk_lote_promo
        FOREIGN KEY (COD_PROMO)
        REFERENCES PROMOCAO (COD_PROMO),

    CONSTRAINT unq_lote_prod
        UNIQUE (COD_PROD, NUM_LOTE),
        
        

    CHECK (EST_LOTE >= 0),

    CHECK (
        DATA_FAB_LOTE IS NULL
        OR DATA_VENC_LOTE > DATA_FAB_LOTE
    )
);CREATE TABLE LOTE (
    COD_LOTE INT PRIMARY KEY AUTO_INCREMENT,
    COD_PROD INT NOT NULL,
    COD_PROMO INT,

    NUM_LOTE VARCHAR(50) NOT NULL,

    DATA_FAB_LOTE DATE,
    DATA_VENC_LOTE DATE NOT NULL,

    EST_LOTE NUMERIC(10, 2) NOT NULL,
    CONSTRAINT fk_lote_prod
        FOREIGN KEY (COD_PROD)
        REFERENCES PRODUTO (COD_PROD),
    CONSTRAINT fk_lote_promo
        FOREIGN KEY (COD_PROMO)
        REFERENCES PROMOCAO (COD_PROMO),
    CONSTRAINT unq_lote_prod
        UNIQUE (COD_PROD, NUM_LOTE),
    CONSTRAINT unq_lote_cod_prod
        UNIQUE (COD_LOTE, COD_PROD),
    CHECK (EST_LOTE >= 0),
    CHECK (DATA_FAB_LOTE IS NULL OR DATA_VENC_LOTE > DATA_FAB_LOTE)
);

CREATE TABLE INF_NUTRICIONAIS (
	COD_NUTRI INT PRIMARY KEY AUTO_INCREMENT,
	COD_PROD INT NOT NULL,
	NUTRIENTE VARCHAR (50) NOT NULL,
    QTD_100G_NUTRI NUMERIC(8, 2) NOT NULL,
    UNI_NUTRI VARCHAR(10) NOT NULL,
    PERC_VD_NUTRI NUMERIC(5, 2),
    CONSTRAINT fk_nutri_prod FOREIGN KEY (COD_PROD) REFERENCES PRODUTO (COD_PROD),
    CONSTRAINT unq_prod_nutri UNIQUE (COD_PROD, NUTRIENTE) -- evita repetir o nutriente
);


CREATE TABLE FORMA_PAGAMENTO (
	COD_PAG INT PRIMARY KEY AUTO_INCREMENT,
    NOME_PAG VARCHAR(15) NOT NULL UNIQUE
);

CREATE TABLE STATUS_PEDIDO (
	COD_STATUS INT PRIMARY KEY AUTO_INCREMENT,
    NOME_STATUS VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE PEDIDO (
	COD_PED INT PRIMARY KEY AUTO_INCREMENT,
    COD_STATUS INT NOT NULL,
    COD_CLI INT NOT NULL,
    DATA_PED DATE NOT NULL,
    TOTAL_PED NUMERIC(10, 2) NOT NULL,
    CONSTRAINT fk_pedido_status FOREIGN KEY (COD_STATUS) REFERENCES STATUS_PEDIDO (COD_STATUS),
    CONSTRAINT fk_pedido_cli FOREIGN KEY (COD_CLI) REFERENCES CLIENTE (COD_CLI)
);

CREATE TABLE VENDA (
	COD_VENDA INT PRIMARY KEY AUTO_INCREMENT,
    COD_PAG INT NOT NULL,
    COD_PED INT, -- se permitirmos venda parcial de pedido, pode continuar assim, se não, UNIQUE
    COD_PROMO INT, -- se for possível adicionar mais de uma promoção na venda, terá que ser criado uma tabela associativa N:N
    DATA_VENDA DATE NOT NULL,
    VALOR_VENDA NUMERIC(10, 2) NOT NULL,
    CONSTRAINT fk_venda_pag FOREIGN KEY (COD_PAG) REFERENCES FORMA_PAGAMENTO (COD_PAG),
    CONSTRAINT fk_venda_ped FOREIGN KEY (COD_PED) REFERENCES PEDIDO (COD_PED),
    CONSTRAINT fk_venda_pro FOREIGN KEY (COD_PROMO) REFERENCES PROMOCAO (COD_PROMO)
);

CREATE TABLE ITEM_PEDIDO (
	COD_PED INT NOT NULL, -- um determinado produto só pode apareceer uma vez dentro de um pedido
    COD_PROD INT NOT NULL, -- se o cliente for adicionar mais dele, só aumenta a quantidade ao invés de ccriar um novo registro
    QTD_PROD NUMERIC(5, 2) NOT NULL,
    VALOR_UNI NUMERIC(8, 2) NOT NULL,
    CONSTRAINT fk_item_ped FOREIGN KEY (COD_PED) REFERENCES PEDIDO (COD_PED),
    CONSTRAINT fk_item_prod FOREIGN KEY (COD_PROD) REFERENCES PRODUTO (COD_PROD),
    CONSTRAINT pk_item_prod_ped PRIMARY KEY (COD_PED, COD_PROD)
);

CREATE TABLE ITEM_PEDIDO_LOTE (
    COD_PED INT NOT NULL,
    COD_PROD INT NOT NULL,
    COD_LOTE INT NOT NULL,
    QTD_LOTE NUMERIC(10, 2) NOT NULL,
    CONSTRAINT pk_item_pedido_lote
        PRIMARY KEY (COD_PED, COD_PROD, COD_LOTE),
    CONSTRAINT fk_ipl_item
        FOREIGN KEY (COD_PED, COD_PROD)
        REFERENCES ITEM_PEDIDO (COD_PED, COD_PROD),
    CONSTRAINT fk_ipl_lote
        FOREIGN KEY (COD_LOTE)
        REFERENCES LOTE (COD_LOTE),
	CONSTRAINT fk_ipl_lote
		FOREIGN KEY (COD_LOTE, COD_PROD)
		REFERENCES LOTE (COD_LOTE, COD_PROD),
    CHECK (QTD_LOTE > 0)
);

